---
- name: add vhosts
  template:
    src: '{{ vhost.template }}'
    dest: '{{ caddy_config_path }}/vhosts.d/{{ vhost.name }}'
    owner: "{{ caddy_system_user }}"
    group: "{{ caddy_system_group }}"
    mode: 0644
  notify: reload caddy
  tags:
    - caddy
    - caddy_vhosts